{
  inputs,
  host,
  ...
}:
let
  vars = import ../../hosts/${host}/variables.nix;
in
{
  imports = [
    ./boot.nix
    ./fonts.nix
    ./hardware.nix
    ./network.nix
    ./ollama.nix
    ./packages.nix
    ./sddm.nix
    ./security.nix
    ./services.nix
    ./system.nix
    ./stylix.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
    ./quickshell.nix
  ];
}
